version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /WDL/umi_alignment_consensus_bqsr.wdl
    testParameterFiles:
    - /WDL/pipeline.json
    authors:
      - name: "Irenaeus Chan"
        email: chani@wustl.edu
    name: ArCCH-Alignment
  - subclass: WDL
    primaryDescriptorPath: /WDL/ArCCH.wdl
    testParameterFiles:
    - /WDL/pipeline.json
    authors:
      - name: "Irenaeus Chan"
        email: chani@wustl.edu
    name: ArCCH
  - subclass: WDL
    primaryDescriptorPath: /WDL/pon2_creation.wdl
    testParameterFiles:
    - /WDL/pipeline.json
    authors:
      - name: "Irenaeus Chan"
        email: chani@wustl.edu
    name: ArCCH-PON2
  - subclass: WDL
    primaryDescriptorPath: /WDL/WGS/Subworkflows/variant_calling.wdl
    testParameterFiles:
    - /WDL/pipeline.json
    authors:
      - name: "Irenaeus Chan"
        email: chani@wustl.edu
    name: ArCCH-WGS-VariantCalling
