--- 
version: 1.2
workflows: 
  - 
    authors: 
      - 
        email: chani@wustl.edu
        name: "Irenaeus Chan"
    primaryDescriptorPath: /WDL/terra_pipeline.wdl
    subclass: WDL
    testParameterFiles: /WDL/pipeline.json
