version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /WDL/terra_pipeline.wdl
    testParameterFiles: 
    - /WDL/pipeline.json
    authors:
      - name: "Irenaeus Chan"
        email: chani@wustl.edu
    name: ArCCH  
  - subclass: WDL
    primaryDescriptorPath: /WDL/pon2_creation.wdl
    testParameterFiles: 
    - /WDL/pipeline.json
    authors:
      - name: "Irenaeus Chan"
        email: chani@wustl.edu
    name: PON
